---
version: "3.8"

services:
  opensearch3-node1:
    image: opensearchproject/opensearch:${OPENSEARCH3_VERSION}
    container_name: opensearch3-node1
    environment:
      - cluster.name=opensearch3-cluster
      - node.name=opensearch3-node1
      - discovery.seed_hosts=opensearch3-node1,opensearch3-node2
      - cluster.initial_master_nodes=opensearch3-node1,opensearch3-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch3-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch3-net
    healthcheck:
      test: ["CMD", "curl", "-f", "-k",
             "-u", "admin:${OPENSEARCH_INITIAL_ADMIN_PASSWORD}",
             "https://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  opensearch3-node2:
    image: opensearchproject/opensearch:${OPENSEARCH3_VERSION}
    container_name: opensearch3-node2
    environment:
      - cluster.name=opensearch3-cluster
      - node.name=opensearch3-node2
      - discovery.seed_hosts=opensearch3-node1,opensearch3-node2
      - cluster.initial_master_nodes=opensearch3-node1,opensearch3-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch3-data2:/usr/share/opensearch/data
    networks:
      - opensearch3-net
    healthcheck:
      test: ["CMD", "curl", "-f", "-k",
             "-u", "admin:${OPENSEARCH_INITIAL_ADMIN_PASSWORD}",
             "https://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  opensearch3-dashboards:
    image: opensearchproject/opensearch-dashboards:${OPENSEARCH3_VERSION}
    container_name: opensearch3-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: >-
        ["https://opensearch3-node1:9200",
        "https://opensearch3-node2:9200"]
    networks:
      - opensearch3-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  opensearch3-data1:
  opensearch3-data2:

networks:
  opensearch3-net:
