---
version: "3.8"

services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK9_VERSION}
    container_name: elasticsearch-9-setup
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        echo "Waiting for Elasticsearch availability";
        until curl -s http://elasticsearch-9:9200 |
          grep -q "missing authentication credentials"; do
          sleep 5;
        done;
        echo "Setting kibana_system password";
        until curl -s -X POST -u "elastic:${ELASTIC_PASSWORD}" \
          -H "Content-Type: application/json" \
          http://elasticsearch-9:9200/_security/user/kibana_system/_password \
          -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do
          sleep 5;
        done;
        echo "All done!";
      '

  elasticsearch-9:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK9_VERSION}
    container_name: elasticsearch-9
    environment:
      - node.name=elasticsearch-9
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata9:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "elastic:${ELASTIC_PASSWORD}",
             "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  kibana-9:
    depends_on:
      setup:
        condition: service_completed_successfully
    image: docker.elastic.co/kibana/kibana:${ELK9_VERSION}
    container_name: kibana-9
    volumes:
      - kibanadata9:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch-9:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  esdata9:
    driver: local
  kibanadata9:
    driver: local
